// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJeN_kE-keI8i9sLgbFPprSGfRKxiYLUo',
    appId: '1:935093031021:web:a89f755d1e8622dcbfef64',
    messagingSenderId: '935093031021',
    projectId: 'reptran-6ccec',
    authDomain: 'reptran-6ccec.firebaseapp.com',
    storageBucket: 'reptran-6ccec.firebasestorage.app',
    measurementId: 'G-7C5TYQFVTH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApxMuTFrAlJtBpHhHROE9alIJ0NbaYfkM',
    appId: '1:935093031021:ios:92ae184db067eaa1bfef64',
    messagingSenderId: '935093031021',
    projectId: 'reptran-6ccec',
    storageBucket: 'reptran-6ccec.firebasestorage.app',
    iosBundleId: 'com.example.reptranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJeN_kE-keI8i9sLgbFPprSGfRKxiYLUo',
    appId: '1:935093031021:web:bb2170d17f4f3d8ebfef64',
    messagingSenderId: '935093031021',
    projectId: 'reptran-6ccec',
    authDomain: 'reptran-6ccec.firebaseapp.com',
    storageBucket: 'reptran-6ccec.firebasestorage.app',
    measurementId: 'G-G96F44CZLK',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApxMuTFrAlJtBpHhHROE9alIJ0NbaYfkM',
    appId: '1:935093031021:ios:92ae184db067eaa1bfef64',
    messagingSenderId: '935093031021',
    projectId: 'reptran-6ccec',
    storageBucket: 'reptran-6ccec.firebasestorage.app',
    iosBundleId: 'com.example.reptranApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RC60RVnoPe0lOk0Ww96rQSuy7GEg3fQ',
    appId: '1:935093031021:android:041f9c9f3bd0793fbfef64',
    messagingSenderId: '935093031021',
    projectId: 'reptran-6ccec',
    storageBucket: 'reptran-6ccec.firebasestorage.app',
  );

}